### ISSUE TITLE
[Fabric API 0.3.0] Registry remapping failed!

### ISSUE THREAD

**Issue by raphydaphy** [valoeghese/TheBiomeOverhaul#3]
When connecting to a server with The Biome Overhaul 1.1.0, you are presented with an error

![Registry Remapping Failed](https://cdn.discordapp.com/attachments/507304429255393324/571595138128674827/Capture.PNG)

**Comment by valoeghese** [comment]
https://github.com/valoeghese/TheBiomeOverhaul/blob/master/src/main/java/valoeghese/biomeoverhaul/world/CustomSurfaceBuilders.java
SurfaceBuilders

**Comment by valoeghese** [comment]
Why would ID maps be different

**Comment by valoeghese** [comment]
Ok thx raphy for helping me solve this through discord

**Comment by valoeghese** [comment]
Lol forgot to do that when I released it
