### ISSUE TITLE
AbstractMethodError: AbstractTreeFeature.generate

### ISSUE THREAD

**Issue by LemmaEOF** [valoeghese/TheBiomeOverhaul#5]
[log](https://paste.ee/p/EFQP8)
When generating a world with trees it, the game crashes from trying to call an abstract method. I put it through K9 and found that the method is `AbstractTreeFeature.generate`, so something might have changed with generation code. This was done in 1.14.1 with Fabric API 0.3.0 and TBO 1.1.1+beta.

**Comment by valoeghese** [comment]
Fixed in unreleased build (and by yourself it seems)

**Comment by valoeghese** [comment]
lol why did I close it when I haven't released the update
