### ISSUE TITLE
Mipmapping is broken

### ISSUE THREAD

**Issue by Phantop** [valoeghese/TheBiomeOverhaul#7]
As the title says, enabling this mod seems to disable mipmapping. Turning off the mod fixes it.

Looks like it is at minimum setting regardless of what the actual setting is (I have it at 4, looks like it's off).

**Comment by valoeghese** [comment]
I don't touch rendering... this is confusing

**Comment by valoeghese** [comment]
Are you sure you've got the right mod??

The only thing I can think of is biome sky colour, but that's a method built in to Minecraft, so it wouldn't be my problem then....
